port: "8000"
postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "qwerty5432" #TODO: need secret k8s
  dbname: "postgres"
  sslmode: "disable"
signing.key: "w4ert&@Nogu%Zl0m1t%u73HbIM"
